[package]
name = "gst-video-thumbnailer"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "GPL-3.0-only"

[dependencies]
gio = { version = "0.21.1", features = ["v2_62"] }
gst = { package = "gstreamer", version = "0.24.3" }
gst-app = { package = "gstreamer-app", version = "0.24.0" }
gst-sys = { package = "gstreamer-sys", version = "0.24.0" }
gst-video = { package = "gstreamer-video", version = "0.24.3" }
gst-tag = { package = "gstreamer-tag", version = "0.24.3" }
image = "0.25.8"
png = "0.18.0"

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "benchmark"
harness = false
